import * as Print from 'expo-print'
import { BillingInvoice, DentalChart, Payment } from '../types'

const escapeHtml = (value: string | null | undefined) => String(value ?? '—').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;')
const money = (value: number) => `₹${Number(value || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const dateLabel = (value: string | null) => value ? new Date(`${value}T00:00:00`).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—'

const documentShell = (clinicName: string, title: string, body: string) => `<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1" /><style>body{font-family:Arial,sans-serif;color:#17323d;padding:28px;line-height:1.45}h1{margin:4px 0 0;font-size:26px}h2{margin:0;color:#087f8c;font-size:14px}p{margin:4px 0;color:#647783;font-size:12px}.header{display:flex;justify-content:space-between;border-bottom:2px solid #087f8c;padding-bottom:18px;margin-bottom:20px}.meta{text-align:right}.summary{display:flex;gap:28px;background:#f0f8f7;border-radius:10px;padding:14px;margin-bottom:20px}.summary strong{display:block;color:#17323d;font-size:14px;margin-top:3px}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{text-align:left;padding:10px 6px;border-bottom:1px solid #e4eeee;font-size:12px}th{text-transform:uppercase;color:#71838e;font-size:10px}td.right,th.right{text-align:right}.totals{margin:18px 0 0 auto;width:260px}.total-row{display:flex;justify-content:space-between;padding:5px 0;font-size:12px}.grand{border-top:2px solid #087f8c;margin-top:5px;padding-top:9px;font-weight:bold;font-size:15px}.footer{margin-top:30px;padding-top:14px;border-top:1px solid #e4eeee;color:#9aaab2;font-size:10px}</style></head><body><div class="header"><div><h2>${escapeHtml(clinicName || 'Clinic')}</h2><h1>${title}</h1></div>${body}</div>`

export async function printInvoice(invoice: BillingInvoice, clinicName: string) {
  const rows = invoice.items.map((item) => `<tr><td>${escapeHtml(item.description)}</td><td class="right">${item.quantity}</td><td class="right">${money(item.unitPrice)}</td><td class="right">${money(item.quantity * item.unitPrice)}</td></tr>`).join('')
  const body = `<div class="meta"><strong>${escapeHtml(invoice.invoiceNumber)}</strong><p>${invoice.status.replace('_', ' ')}</p></div></div><div class="summary"><div><p>Patient</p><strong>${escapeHtml(invoice.patientName)}</strong></div><div><p>Issue date</p><strong>${dateLabel(invoice.issueDate)}</strong></div><div><p>Due date</p><strong>${dateLabel(invoice.dueDate)}</strong></div></div><table><thead><tr><th>Description</th><th class="right">Qty</th><th class="right">Unit price</th><th class="right">Amount</th></tr></thead><tbody>${rows}</tbody></table><div class="totals"><div class="total-row"><span>Subtotal</span><strong>${money(invoice.subtotal)}</strong></div><div class="total-row"><span>Discount</span><strong>${money(invoice.discount)}</strong></div><div class="total-row"><span>Tax</span><strong>${money(invoice.tax)}</strong></div><div class="total-row grand"><span>Total</span><strong>${money(invoice.total)}</strong></div><div class="total-row"><span>Paid</span><strong>${money(invoice.paidAmount)}</strong></div><div class="total-row"><span>Balance</span><strong>${money(invoice.balance)}</strong></div></div><div class="footer">Generated from ${escapeHtml(clinicName || 'Clinic')} · ${new Date().toLocaleString('en-IN')}</div>`
  const html = `${documentShell(clinicName, 'Invoice', body)}</body></html>`
  await Print.printAsync({ html })
}

export async function printReceipt(payment: Payment, clinicName: string) {
  const notes = payment.notes ? `<tr><th>Notes</th><td>${escapeHtml(payment.notes)}</td></tr>` : ''
  const body = `<div class="meta"><strong>${escapeHtml(payment.receiptNumber)}</strong><p>${escapeHtml(payment.invoiceNumber)}</p></div></div><div class="summary"><div><p>Patient</p><strong>${escapeHtml(payment.patientName)}</strong></div><div><p>Payment date</p><strong>${dateLabel(payment.paymentDate)}</strong></div><div><p>Amount paid</p><strong>${money(payment.amount)}</strong></div></div><table><tbody><tr><th>Receipt number</th><td>${escapeHtml(payment.receiptNumber)}</td></tr><tr><th>Invoice number</th><td>${escapeHtml(payment.invoiceNumber)}</td></tr><tr><th>Payment method</th><td>${escapeHtml(payment.method.replace('_', ' '))}</td></tr><tr><th>Reference</th><td>${escapeHtml(payment.reference || '—')}</td></tr>${notes}</tbody></table><div class="totals"><div class="total-row grand"><span>Amount paid</span><strong>${money(payment.amount)}</strong></div></div><div class="footer">Generated from ${escapeHtml(clinicName || 'Clinic')} · ${new Date().toLocaleString('en-IN')}</div>`
  const html = `${documentShell(clinicName, 'Payment Receipt', body)}</body></html>`
  await Print.printAsync({ html })
}

export async function printDentalChart(chart: DentalChart, clinicName: string) {
  const labels: Record<string, string> = { CARIES: 'Caries', FILLED: 'Filled', MISSING: 'Missing', CROWN: 'Crown', ROOT_CANAL: 'Root canal', IMPLANT: 'Implant', FRACTURE: 'Fracture' }
  const rows = Object.entries(chart.toothStatuses).filter(([, status]) => status !== 'HEALTHY').map(([tooth, status]) => `<tr><td>${escapeHtml(tooth)}</td><td>${escapeHtml(labels[status] || status)}</td></tr>`).join('')
  const body = `<div class="meta"><strong>FDI notation</strong><p>Printed ${new Date().toLocaleDateString('en-IN')}</p></div></div><div class="summary"><div><p>Patient</p><strong>${escapeHtml(chart.patientName)}</strong></div><div><p>Marked teeth</p><strong>${Object.keys(chart.toothStatuses).filter((tooth) => chart.toothStatuses[tooth] !== 'HEALTHY').length} of 32</strong></div><div><p>Phone</p><strong>${escapeHtml(chart.phone || '—')}</strong></div></div><table><thead><tr><th>Tooth</th><th>Condition</th></tr></thead><tbody>${rows || '<tr><td colspan="2">No tooth conditions marked</td></tr>'}</tbody></table>${chart.notes ? `<div class="footer"><strong>Clinical notes</strong><br/>${escapeHtml(chart.notes)}</div>` : ''}<div class="footer">Generated from ${escapeHtml(clinicName || 'Clinic')} · ${new Date().toLocaleString('en-IN')}</div>`
  const html = `${documentShell(clinicName, 'Dental Chart', body)}</body></html>`
  await Print.printAsync({ html })
}
