import { FormEvent, useEffect, useState } from 'react'
import { Building2, Mail, MapPin, Pencil, Phone, Plus, Trash2, X } from 'lucide-react'
import { apiDelete, apiGet, apiPost, apiPut, Branch } from '../api'
import { EmptyState, ErrorState, LoadingState } from '../components/PageStates'

type BranchForm = { name: string; code: string; phone: string; email: string; address: string; city: string; state: string; postalCode: string; active: boolean }
const emptyForm: BranchForm = { name: '', code: '', phone: '', email: '', address: '', city: '', state: '', postalCode: '', active: true }
function fromBranch(branch: Branch): BranchForm { return { name: branch.name, code: branch.code, phone: branch.phone ?? '', email: branch.email ?? '', address: branch.address ?? '', city: branch.city ?? '', state: branch.state ?? '', postalCode: branch.postalCode ?? '', active: branch.active } }

export default function BranchPage() {
  const [branches, setBranches] = useState<Branch[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [form, setForm] = useState<BranchForm>(emptyForm)
  const [editing, setEditing] = useState<Branch | null>(null)
  const [formOpen, setFormOpen] = useState(false)
  const [saving, setSaving] = useState(false)
  const loadBranches = () => { setLoading(true); setError(''); apiGet<Branch[]>('/api/branches').then(setBranches).catch((requestError) => setError(requestError instanceof Error ? requestError.message : 'Unable to load branches')).finally(() => setLoading(false)) }
  useEffect(() => { loadBranches() }, [])
  const openCreate = () => { setEditing(null); setForm(emptyForm); setFormOpen(true); setError('') }
  const openEdit = (branch: Branch) => { setEditing(branch); setForm(fromBranch(branch)); setFormOpen(true); setError('') }
  const closeForm = () => { setEditing(null); setFormOpen(false); setForm(emptyForm) }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(''); try { const saved = editing ? await apiPut<Branch>(`/api/branches/${editing.id}`, form) : await apiPost<Branch>('/api/branches', form); setBranches((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [...current, saved].sort((a, b) => a.name.localeCompare(b.name))); closeForm() } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to save branch') } finally { setSaving(false) } }
  async function remove(branch: Branch) { if (!window.confirm(`Delete ${branch.name}?`)) return; try { await apiDelete(`/api/branches/${branch.id}`); setBranches((current) => current.filter((item) => item.id !== branch.id)) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to delete branch') } }

  return <div className="space-y-6 py-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><p className="text-sm text-muted">Manage the clinic locations available to your team.</p><button onClick={openCreate} className="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-600 px-4 py-3 text-xs font-bold text-white shadow-lg shadow-teal-600/20 hover:bg-teal-700"><Plus size={16} /> Add branch</button></div>{error && !formOpen && <p className="rounded-xl bg-rose-50 px-4 py-3 text-xs font-semibold text-rose-600">{error}</p>}{loading ? <LoadingState /> : error && branches.length === 0 ? <ErrorState message={error} onRetry={loadBranches} /> : branches.length === 0 ? <EmptyState title="No branches found" description="Create a branch to assign doctors and organize clinic operations." /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{branches.map((branch) => <div key={branch.id} className="rounded-2xl border border-slate-100 bg-white p-5 shadow-soft"><div className="flex items-start justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-teal-50 text-teal-600"><Building2 size={20} /></span><div className="flex gap-1"><button onClick={() => openEdit(branch)} className="rounded-lg p-2 text-slate-400 hover:bg-teal-50 hover:text-teal-600"><Pencil size={15} /></button><button onClick={() => remove(branch)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={15} /></button></div></div><div className="mt-4 flex items-center gap-2"><h3 className="heading-font text-base font-extrabold text-ink">{branch.name}</h3><span className="rounded-md bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-500">{branch.code}</span></div><span className={`mt-2 inline-flex rounded-md px-2 py-1 text-[10px] font-bold ${branch.active ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-100 text-slate-500'}`}>{branch.active ? 'Active' : 'Inactive'}</span><div className="mt-5 space-y-2 border-t border-slate-100 pt-4 text-xs text-muted"><p className="flex items-center gap-2"><MapPin size={14} />{[branch.address, branch.city, branch.state, branch.postalCode].filter(Boolean).join(', ') || 'Address not recorded'}</p><p className="flex items-center gap-2"><Phone size={14} />{branch.phone || 'Phone not recorded'}</p><p className="flex items-center gap-2"><Mail size={14} />{branch.email || 'Email not recorded'}</p></div></div>)}</div>}{formOpen && <BranchModal editing={editing} form={form} setForm={setForm} saving={saving} error={error} onClose={closeForm} onSave={save} />}</div>
}

function BranchModal({ editing, form, setForm, saving, error, onClose, onSave }: { editing: Branch | null; form: BranchForm; setForm: (form: BranchForm) => void; saving: boolean; error: string; onClose: () => void; onSave: (event: FormEvent<HTMLFormElement>) => void }) {
  return <div className="fixed inset-0 z-[70] flex items-end justify-center bg-ink/30 p-0 backdrop-blur-sm sm:items-center sm:p-5"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white p-6 shadow-2xl sm:rounded-3xl"><div className="flex items-start justify-between"><div><h2 className="heading-font text-xl font-extrabold text-ink">{editing ? 'Edit branch' : 'Add branch'}</h2><p className="mt-1 text-xs text-muted">Keep branch contact information up to date.</p></div><button onClick={onClose} className="rounded-lg p-2 text-muted hover:bg-slate-100"><X size={18} /></button></div><form onSubmit={onSave} className="mt-6 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Branch name" required value={form.name} onChange={(value) => setForm({ ...form, name: value })} /><Field label="Branch code" required value={form.code} onChange={(value) => setForm({ ...form, code: value })} /><Field label="Phone" value={form.phone} onChange={(value) => setForm({ ...form, phone: value })} /><Field label="Email" type="email" value={form.email} onChange={(value) => setForm({ ...form, email: value })} /><Field label="Address" value={form.address} onChange={(value) => setForm({ ...form, address: value })} /><Field label="City" value={form.city} onChange={(value) => setForm({ ...form, city: value })} /><Field label="State" value={form.state} onChange={(value) => setForm({ ...form, state: value })} /><Field label="Postal code" value={form.postalCode} onChange={(value) => setForm({ ...form, postalCode: value })} /></div><label className="flex items-center gap-3 rounded-xl border border-slate-200 px-3 py-3 text-xs font-bold text-ink"><input type="checkbox" checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })} className="h-4 w-4 accent-teal-600" />Branch is active</label>{error && <p className="rounded-xl bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-600">{error}</p>}<div className="flex justify-end gap-3 border-t border-slate-100 pt-5"><button type="button" onClick={onClose} className="rounded-xl px-4 py-2.5 text-xs font-bold text-muted hover:bg-slate-100">Cancel</button><button disabled={saving} className="rounded-xl bg-teal-600 px-5 py-2.5 text-xs font-bold text-white hover:bg-teal-700 disabled:opacity-60">{saving ? 'Saving...' : editing ? 'Save changes' : 'Create branch'}</button></div></form></div></div>
}
function Field({ label, value, onChange, type = 'text', required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="block"><span className="mb-1.5 block text-xs font-bold text-ink">{label}{required && <span className="text-coral"> *</span>}</span><input required={required} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-teal-500 focus:ring-4 focus:ring-teal-500/10" /></label> }
