import { FormEvent, useEffect, useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import { ArrowLeft, CalendarDays, Download, FileText, HeartPulse, Paperclip, Pill, Receipt, Save, Stethoscope, Trash2, Upload, UserRound } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { apiDelete, apiGet, apiPut, apiUpload, Appointment, BillingInvoice, Consultation, Patient, PatientAttachment, Payment, TreatmentPlan } from '../api'
import { ErrorState, LoadingState } from '../components/PageStates'

type DentalChart = { notes: string | null; toothStatuses: Record<string, string>; updatedAt: string | null }
type ProfileForm = { allergies: string; medications: string; medicalHistory: string; medicalNotes: string }

const dateText = (value: string | null | undefined) => value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : '—'
const money = (value: number) => new Intl.NumberFormat(undefined, { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(value || 0)

export default function PatientProfilePage() {
  const { id } = useParams(); const navigate = useNavigate(); const patientId = Number(id)
  const [patient, setPatient] = useState<Patient | null>(null)
  const [consultations, setConsultations] = useState<Consultation[]>([])
  const [appointments, setAppointments] = useState<Appointment[]>([])
  const [plans, setPlans] = useState<TreatmentPlan[]>([])
  const [invoices, setInvoices] = useState<BillingInvoice[]>([])
  const [payments, setPayments] = useState<Payment[]>([])
  const [attachments, setAttachments] = useState<PatientAttachment[]>([])
  const [chart, setChart] = useState<DentalChart | null>(null)
  const [form, setForm] = useState<ProfileForm>({ allergies: '', medications: '', medicalHistory: '', medicalNotes: '' })
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [uploading, setUploading] = useState(false)

  const load = () => {
    if (!patientId) return
    setLoading(true); setError('')
    Promise.all([
      apiGet<Patient>(`/api/patients/${patientId}`),
      apiGet<Consultation[]>('/api/consultations'), apiGet<Appointment[]>('/api/appointments'), apiGet<TreatmentPlan[]>('/api/treatment-plans'),
      apiGet<BillingInvoice[]>('/api/billing/invoices'), apiGet<Payment[]>('/api/payments'), apiGet<PatientAttachment[]>(`/api/patients/${patientId}/attachments`),
      apiGet<DentalChart>(`/api/dental-charts/${patientId}`),
    ]).then(([patientData, consultationData, appointmentData, planData, invoiceData, paymentData, attachmentData, chartData]) => {
      setPatient(patientData); setForm({ allergies: patientData.allergies ?? '', medications: patientData.medications ?? '', medicalHistory: patientData.medicalHistory ?? '', medicalNotes: patientData.medicalNotes ?? '' })
      setConsultations(consultationData.filter((item) => item.patientId === patientId)); setAppointments(appointmentData.filter((item) => item.patientId === patientId)); setPlans(planData.filter((item) => item.patientId === patientId)); setInvoices(invoiceData.filter((item) => item.patientId === patientId)); setPayments(paymentData.filter((item) => item.patientId === patientId)); setAttachments(attachmentData); setChart(chartData)
    }).catch((requestError) => setError(requestError instanceof Error ? requestError.message : 'Unable to load patient profile')).finally(() => setLoading(false))
  }
  useEffect(() => { load() }, [patientId])

  const timeline = useMemo(() => [
    ...consultations.map((item) => ({ date: item.consultationDateTime, kind: 'Consultation', title: item.diagnosis || item.chiefComplaint || 'Clinical consultation', detail: `${item.doctorName} · ${item.status}` })),
    ...appointments.map((item) => ({ date: item.appointmentDateTime, kind: 'Appointment', title: item.appointmentType, detail: `${item.doctorName} · ${item.status}` })),
    ...plans.map((item) => ({ date: item.startDate || '', kind: 'Treatment plan', title: item.title, detail: `${item.status} · ${money(item.estimatedTotal)}` })),
    ...invoices.map((item) => ({ date: item.issueDate, kind: 'Invoice', title: item.invoiceNumber, detail: `${item.status} · ${money(item.total)}` })),
    ...payments.map((item) => ({ date: item.paymentDate, kind: 'Payment', title: item.receiptNumber, detail: `${item.method} · ${money(item.amount)}` })),
  ].sort((a, b) => String(b.date).localeCompare(String(a.date))), [consultations, appointments, plans, invoices, payments])

  async function saveProfile(event: FormEvent) { event.preventDefault(); if (!patient) return; setSaving(true); setError(''); try { const saved = await apiPut<Patient>(`/api/patients/${patient.id}`, { ...patient, ...form }); setPatient(saved) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to save profile') } finally { setSaving(false) } }
  async function upload(file: File) { setUploading(true); setError(''); try { const saved = await apiUpload<PatientAttachment>(`/api/patients/${patientId}/attachments`, file); setAttachments((current) => [saved, ...current]) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to upload attachment') } finally { setUploading(false) } }
  async function download(item: PatientAttachment) { const token = localStorage.getItem('dentahub_token'); const response = await fetch(`/api/patients/${patientId}/attachments/${item.id}`, { headers: token ? { Authorization: `Bearer ${token}` } : {} }); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = item.fileName; link.click(); URL.revokeObjectURL(url) }
  async function removeAttachment(item: PatientAttachment) { if (!window.confirm(`Delete ${item.fileName}?`)) return; try { await apiDelete(`/api/patients/${patientId}/attachments/${item.id}`); setAttachments((current) => current.filter((value) => value.id !== item.id)) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to delete attachment') } }

  if (loading) return <LoadingState />
  if (error && !patient) return <ErrorState message={error} onRetry={load} />
  if (!patient) return <ErrorState message="Patient was not found" onRetry={load} />
  return <div className="space-y-6 py-7">
    <button onClick={() => navigate('/patients')} className="inline-flex items-center gap-2 text-xs font-bold text-muted hover:text-teal-700"><ArrowLeft size={15} /> Back to patients</button>
    <section className="rounded-3xl bg-gradient-to-br from-[#087f8c] to-[#46b7ac] p-6 text-white shadow-lg sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div className="flex items-center gap-4"><span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-white/15"><UserRound size={30} /></span><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-50/70">Patient profile</p><h1 className="heading-font mt-1 text-2xl font-extrabold">{patient.fullName}</h1><p className="mt-1 text-sm text-teal-50/80">{patient.phone} {patient.email ? `· ${patient.email}` : ''}</p></div></div><span className="rounded-lg bg-white/15 px-3 py-1.5 text-xs font-bold">{patient.status}</span></div><div className="mt-7 grid gap-4 text-sm sm:grid-cols-4"><ProfileStat label="Date of birth" value={patient.dateOfBirth || 'Not recorded'} /><ProfileStat label="Gender" value={patient.gender || 'Not recorded'} /><ProfileStat label="Appointments" value={String(appointments.length)} /><ProfileStat label="Outstanding" value={money(invoices.reduce((sum, item) => sum + item.balance, 0))} /></div></section>
    {error && <p className="rounded-xl bg-rose-50 px-4 py-3 text-xs font-semibold text-rose-600">{error}</p>}
    <div className="grid gap-6 xl:grid-cols-[1.35fr_1fr]">
      <section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-soft sm:p-6"><SectionTitle icon={<CalendarDays size={18} />} title="Patient timeline" caption="Consultations, visits, plans, invoices and payments" /><div className="mt-5 space-y-4">{timeline.length === 0 ? <p className="text-sm text-muted">No activity recorded yet.</p> : timeline.map((item, index) => <div key={`${item.kind}-${item.date}-${index}`} className="flex gap-3"><span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-teal-500 ring-4 ring-teal-50" /><div className="min-w-0 flex-1 border-b border-slate-100 pb-4"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-bold text-ink">{item.title}</p><span className="text-[11px] text-muted">{dateText(item.date)}</span></div><p className="mt-1 text-xs text-muted">{item.kind} · {item.detail}</p></div></div>)}</div></section>
      <div className="space-y-6"><section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-soft sm:p-6"><SectionTitle icon={<HeartPulse size={18} />} title="Medical profile" caption="Keep key clinical information current" /><form onSubmit={saveProfile} className="mt-5 space-y-4"><TextArea label="Allergies" value={form.allergies} onChange={(value) => setForm({ ...form, allergies: value })} placeholder="Medication, latex, food allergies..." /><TextArea label="Current medications" value={form.medications} onChange={(value) => setForm({ ...form, medications: value })} placeholder="Medicine and dosage" /><TextArea label="Medical history" value={form.medicalHistory} onChange={(value) => setForm({ ...form, medicalHistory: value })} placeholder="Relevant medical conditions and surgeries" /><TextArea label="Clinical notes" value={form.medicalNotes} onChange={(value) => setForm({ ...form, medicalNotes: value })} /><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-60"><Save size={15} />{saving ? 'Saving...' : 'Save medical profile'}</button></form></section><section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-soft sm:p-6"><SectionTitle icon={<Stethoscope size={18} />} title="Dental chart" caption={`${Object.keys(chart?.toothStatuses ?? {}).length} teeth marked`} /><p className="mt-4 text-xs leading-5 text-muted">{chart?.notes || 'No dental chart notes recorded.'}</p><button onClick={() => navigate(`/dental-chart?patientId=${patient.id}`)} className="mt-4 text-xs font-bold text-teal-700 hover:text-teal-900">Open dental chart →</button></section></div>
    </div>
    <div className="grid gap-6 lg:grid-cols-2"><HistoryCard title="Previous consultations" icon={<Stethoscope size={18} />} empty="No consultations yet." items={consultations.map((item) => `${dateText(item.consultationDateTime)} · ${item.diagnosis || item.chiefComplaint || 'Consultation'} · ${item.doctorName}`)} /><HistoryCard title="Treatment history" icon={<Pill size={18} />} empty="No treatment plans yet." items={plans.map((item) => `${item.title} · ${item.status} · ${money(item.estimatedTotal)}`)} /><HistoryCard title="Invoice & payment history" icon={<Receipt size={18} />} empty="No invoices or payments yet." items={[...invoices.map((item) => `${item.invoiceNumber} · ${item.status} · ${money(item.total)} (${money(item.balance)} due)`), ...payments.map((item) => `${item.receiptNumber} · ${item.method} · ${money(item.amount)}`)]} /><AttachmentCard attachments={attachments} uploading={uploading} onUpload={upload} onDownload={download} onDelete={removeAttachment} /></div>
  </div>
}

function ProfileStat({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-teal-50/70">{label}</p><p className="mt-1 font-bold">{value}</p></div> }
function SectionTitle({ icon, title, caption }: { icon: ReactNode; title: string; caption: string }) { return <div className="flex items-start gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-teal-50 text-teal-600">{icon}</span><div><h2 className="heading-font text-base font-extrabold text-ink">{title}</h2><p className="mt-1 text-xs text-muted">{caption}</p></div></div> }
function TextArea({ label, value, onChange, placeholder = '' }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) { return <label className="block"><span className="mb-1.5 block text-xs font-bold text-ink">{label}</span><textarea rows={3} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className="w-full resize-none rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none placeholder:text-slate-400 focus:border-teal-500 focus:ring-4 focus:ring-teal-500/10" /></label> }
function HistoryCard({ title, icon, items, empty }: { title: string; icon: ReactNode; items: string[]; empty: string }) { return <section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-soft"><SectionTitle icon={icon} title={title} caption="Latest records" /><div className="mt-4 space-y-2">{items.length === 0 ? <p className="text-sm text-muted">{empty}</p> : items.map((item, index) => <p key={index} className="rounded-xl bg-slate-50 px-3 py-2.5 text-xs leading-5 text-ink">{item}</p>)}</div></section> }
function AttachmentCard({ attachments, uploading, onUpload, onDownload, onDelete }: { attachments: PatientAttachment[]; uploading: boolean; onUpload: (file: File) => void; onDownload: (item: PatientAttachment) => void; onDelete: (item: PatientAttachment) => void }) { return <section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-soft"><SectionTitle icon={<Paperclip size={18} />} title="Documents & scans" caption="X-rays, prescriptions, scans and other files" /><label className="mt-4 flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-teal-200 bg-teal-50/50 px-4 py-4 text-xs font-bold text-teal-700 hover:bg-teal-50"><Upload size={16} />{uploading ? 'Uploading...' : 'Attach a file'}<input type="file" accept="image/*,.pdf,.doc,.docx" disabled={uploading} onChange={(event) => { const file = event.target.files?.[0]; if (file) onUpload(file); event.currentTarget.value = '' }} className="hidden" /></label><div className="mt-4 space-y-2">{attachments.length === 0 ? <p className="text-sm text-muted">No attachments yet.</p> : attachments.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl border border-slate-100 px-3 py-2.5"><FileText size={16} className="shrink-0 text-teal-600" /><p className="min-w-0 flex-1 truncate text-xs font-semibold text-ink">{item.fileName}<span className="ml-2 text-[10px] font-normal text-muted">{Math.ceil(item.fileSize / 1024)} KB</span></p><button onClick={() => onDownload(item)} aria-label={`Download ${item.fileName}`} className="rounded-lg p-1.5 text-muted hover:bg-teal-50 hover:text-teal-700"><Download size={15} /></button><button onClick={() => onDelete(item)} aria-label={`Delete ${item.fileName}`} className="rounded-lg p-1.5 text-muted hover:bg-rose-50 hover:text-rose-700"><Trash2 size={15} /></button></div>)}</div></section> }
