import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Clock3, FileText, Pencil, Plus, Search, Tag, Trash2, X } from 'lucide-react'
import { apiDelete, apiGet, apiPost, apiPut, Treatment } from '../api'
import { EmptyState, ErrorState, LoadingState } from '../components/PageStates'

type TreatmentForm = { name: string; category: string; description: string; durationMinutes: string; price: string; active: boolean }
const emptyForm: TreatmentForm = { name: '', category: '', description: '', durationMinutes: '', price: '', active: true }
function fromTreatment(item: Treatment): TreatmentForm { return { name: item.name, category: item.category ?? '', description: item.description ?? '', durationMinutes: item.durationMinutes?.toString() ?? '', price: item.price?.toString() ?? '', active: item.active } }
function money(value: number) { return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(value || 0) }

export default function TreatmentsPage() {
  const [treatments, setTreatments] = useState<Treatment[]>([])
  const [search, setSearch] = useState('')
  const [statusFilter, setStatusFilter] = useState('ALL')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [form, setForm] = useState<TreatmentForm>(emptyForm)
  const [editing, setEditing] = useState<Treatment | null>(null)
  const [formOpen, setFormOpen] = useState(false)
  const [saving, setSaving] = useState(false)

  const load = () => { setLoading(true); setError(''); apiGet<Treatment[]>(`/api/treatments?q=${encodeURIComponent(search)}`).then(setTreatments).catch((requestError) => setError(requestError instanceof Error ? requestError.message : 'Unable to load treatments')).finally(() => setLoading(false)) }
  useEffect(() => { const timer = window.setTimeout(load, 250); return () => window.clearTimeout(timer) }, [search])
  const visible = useMemo(() => treatments.filter((item) => statusFilter === 'ALL' || (statusFilter === 'ACTIVE' ? item.active : !item.active)), [treatments, statusFilter])
  const openCreate = () => { setEditing(null); setForm(emptyForm); setFormOpen(true); setError('') }
  const openEdit = (item: Treatment) => { setEditing(item); setForm(fromTreatment(item)); setFormOpen(true); setError('') }
  const closeForm = () => { setEditing(null); setFormOpen(false); setForm(emptyForm) }

  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setError('')
    try {
      const payload = { ...form, durationMinutes: form.durationMinutes ? Number(form.durationMinutes) : null, price: form.price ? Number(form.price) : 0 }
      const saved = editing ? await apiPut<Treatment>(`/api/treatments/${editing.id}`, payload) : await apiPost<Treatment>('/api/treatments', payload)
      setTreatments((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [...current, saved].sort((a, b) => a.name.localeCompare(b.name)))
      closeForm()
    } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to save treatment') } finally { setSaving(false) }
  }

  async function remove(item: Treatment) {
    if (!window.confirm(`Delete ${item.name}?`)) return
    try { await apiDelete(`/api/treatments/${item.id}`); setTreatments((current) => current.filter((value) => value.id !== item.id)) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to delete treatment') }
  }

  return <div className="space-y-6 py-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm text-muted">Maintain the treatments your clinic offers and their standard pricing.</p></div><button onClick={openCreate} className="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-600 px-4 py-3 text-xs font-bold text-white shadow-lg shadow-teal-600/20 hover:bg-teal-700"><Plus size={16} /> Add treatment</button></div><div className="flex flex-col gap-3 rounded-2xl border border-slate-100 bg-white p-3 shadow-soft sm:flex-row"><div className="flex flex-1 items-center gap-3 rounded-xl border border-slate-200 px-3.5 py-2.5 focus-within:border-teal-500 focus-within:ring-4 focus-within:ring-teal-500/10"><Search size={17} className="text-muted" /><input value={search} onChange={(event) => setSearch(event.target.value)} className="w-full bg-transparent text-sm outline-none placeholder:text-slate-400" placeholder="Search treatment or category" /></div><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-ink outline-none"><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></div>{error && !formOpen && <p className="rounded-xl bg-rose-50 px-4 py-3 text-xs font-semibold text-rose-600">{error}</p>}{loading ? <LoadingState /> : error && treatments.length === 0 ? <ErrorState message={error} onRetry={load} /> : visible.length === 0 ? <EmptyState title="No treatments found" description="Add the clinic treatments that can be used in treatment plans." /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((item) => <TreatmentCard key={item.id} item={item} onEdit={openEdit} onDelete={remove} />)}</div>}{formOpen && <TreatmentModal editing={editing} form={form} setForm={setForm} saving={saving} error={error} onClose={closeForm} onSave={save} />}</div>
}

function TreatmentCard({ item, onEdit, onDelete }: { item: Treatment; onEdit: (item: Treatment) => void; onDelete: (item: Treatment) => void }) { return <article className="rounded-2xl border border-slate-100 bg-white p-5 shadow-soft"><div className="flex items-start justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-teal-50 text-teal-600"><Tag size={20} /></span><div className="flex gap-1"><button onClick={() => onEdit(item)} aria-label={`Edit ${item.name}`} className="rounded-lg p-2 text-slate-400 hover:bg-teal-50 hover:text-teal-600"><Pencil size={15} /></button><button onClick={() => onDelete(item)} aria-label={`Delete ${item.name}`} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={15} /></button></div></div><div className="mt-4 flex items-start justify-between gap-3"><div><h3 className="heading-font text-base font-extrabold text-ink">{item.name}</h3><p className="mt-1 text-xs text-muted">{item.category || 'General treatment'}</p></div><span className={`rounded-md px-2 py-1 text-[10px] font-bold ${item.active ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-100 text-slate-500'}`}>{item.active ? 'Active' : 'Inactive'}</span></div><p className="mt-4 min-h-10 text-xs leading-5 text-muted">{item.description || 'No description added.'}</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4"><span className="flex items-center gap-1.5 text-xs font-semibold text-muted"><Clock3 size={14} />{item.durationMinutes ? `${item.durationMinutes} min` : 'Duration not set'}</span><span className="text-sm font-extrabold text-teal-700">{money(item.price)}</span></div></article> }

function TreatmentModal({ editing, form, setForm, saving, error, onClose, onSave }: { editing: Treatment | null; form: TreatmentForm; setForm: (form: TreatmentForm) => void; saving: boolean; error: string; onClose: () => void; onSave: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="fixed inset-0 z-[70] flex items-end justify-center bg-ink/30 p-0 backdrop-blur-sm sm:items-center sm:p-5"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white p-6 shadow-2xl sm:rounded-3xl"><div className="flex items-start justify-between"><div><h2 className="heading-font text-xl font-extrabold text-ink">{editing ? 'Edit treatment' : 'Add treatment'}</h2><p className="mt-1 text-xs text-muted">Add the clinical and pricing details used across treatment plans.</p></div><button onClick={onClose} className="rounded-lg p-2 text-muted hover:bg-slate-100"><X size={18} /></button></div><form onSubmit={onSave} className="mt-6 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Treatment name" required value={form.name} onChange={(value) => setForm({ ...form, name: value })} /><Field label="Category" value={form.category} onChange={(value) => setForm({ ...form, category: value })} /><Field label="Duration (minutes)" type="number" value={form.durationMinutes} onChange={(value) => setForm({ ...form, durationMinutes: value })} /><Field label="Standard price" type="number" value={form.price} onChange={(value) => setForm({ ...form, price: value })} /></div><label className="block"><span className="mb-1.5 block text-xs font-bold text-ink">Description</span><textarea rows={4} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className="w-full resize-none rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-teal-500 focus:ring-4 focus:ring-teal-500/10" /></label><label className="flex items-center gap-3 rounded-xl border border-slate-200 px-3 py-3 text-xs font-bold text-ink"><input type="checkbox" checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })} className="h-4 w-4 accent-teal-600" />Available for new treatment plans</label>{error && <p className="rounded-xl bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-600">{error}</p>}<div className="flex justify-end gap-3 border-t border-slate-100 pt-5"><button type="button" onClick={onClose} className="rounded-xl px-4 py-2.5 text-xs font-bold text-muted hover:bg-slate-100">Cancel</button><button disabled={saving} className="rounded-xl bg-teal-600 px-5 py-2.5 text-xs font-bold text-white hover:bg-teal-700 disabled:opacity-60">{saving ? 'Saving...' : editing ? 'Save changes' : 'Create treatment'}</button></div></form></div></div> }
function Field({ label, value, onChange, type = 'text', required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="block"><span className="mb-1.5 block text-xs font-bold text-ink">{label}{required && <span className="text-coral"> *</span>}</span><input required={required} min={type === 'number' ? 0 : undefined} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-teal-500 focus:ring-4 focus:ring-teal-500/10" /></label> }
